### ISSUE TITLE
Tracking: Improvements to MechDB Viewer

### ISSUE THREAD

**Issue by infinitymdm** [mechtronica/mechtronica.net#71]
This is a tracking issue for problems, nitpicks, and other complaints related to the MechDB viewer. Most of the tasks listed below should probably turn into their own issues.

Issues
- [ ] MechDB viewer isn't mobile friendly (and isn't super pleasant to use in a desktop browser either)
- [ ] Fix scrollbar placement. Scrollbars shouldn't be below the sticky footer bar
- [ ] The sticky footer bar doesn't fill the whole width of the MechDB viewer table.
- [ ] Scrollbars disappear/reappear when the frame view modal is opened/closed. This means every time you view a frame, the page gets scrolled up just a little, which is super annoying.

Improvement Ideas
- [ ] If I'm filtering by any single attribute, hide that attribute in the table. (e.g. if sorting to only view frames, hide the type column)

**Comment by Icosahunter** [comment]
I fixed a lot of the issues with scrollbars in my mech-builder page I'm working on, I can copy some of that work over to the main mechdb viewer.
